### ISSUE TITLE
redirect to home page issue

### ISSUE THREAD

**Issue by Bapan-Ghosh** [Amraneze/react-instagram-login#5]
"@amraneze/react-instagram-login": "^3.0.4", after this update it's not redirecting to home page instead it's going to the profile of that insta account

**Comment by Amraneze** [comment]
Hi @Bapan-Ghosh I will check it out today

**Comment by Amraneze** [comment]
@Bapan-Ghosh Can you try with the version `3.0.5`. I updated the [sandbox code](https://codesandbox.io/s/amraneze-react-instagram-login-gggjr?file=/src/App.js)

**Comment by Amraneze** [comment]
This issue will be closed for now. @Bapan-Ghosh feel free to open a new issue if you you encountered an issue I will be happy to fix it
